### ISSUE TITLE
Separate Python even more?

### ISSUE THREAD

**Issue by devmotion** [JuliaOptimalTransport/OptimalTransport.jl#42]
I am implementing a Python interface for one of my packages with pyjulia. The package depends on OptimalTransport but since POT was quite annoying to install (there's a bug in pip and therefore one always has to install cython and numpy first, otherwise installation will fail) I completely switched to OptimalTransport + Tulip, eliminating all Python dependencies. However, pyjulia requires PyCall and installs and loads it automatically, and therefore automatically also the POT submodule in OptimalTransport is loaded even though I don't want to use it. And now Python users either have to install POT which is quite annoying and also problematic for CI (and it's not even used at all!), or they'll get an error message when OptimalTransport tries to load it in https://github.com/zsteve/OptimalTransport.jl/blob/9ad8f733770b7cd446c84ebfc90e2a558d6d120b/src/pot.jl#L8.

Maybe the Python interface to POT could be moved to a completely separate package or one could require users to load, and possibly install, it explicitly by making the `__init__` function a proper function that could be called e.g. `load_POT!`.

**Comment by devmotion** [comment]
I fixed the issue for now by removing the dependency on OptimalTransport and reimplementing the LP formulation in my package. I'll open a PR with the version in my package since it seems to be simpler, more efficient, and requires fewer dependencies.

**Comment by devmotion** [comment]
I extracted the POT interface into a separate package: https://github.com/devmotion/POT.jl

**Comment by zsteve** [comment]
Hi @devmotion ,
Thanks for the proposal and for contributing the separate package! This sounds fine, and I agree that moving forward separating out the POT component will make things easier in terms of dependencies and also in general.
I will reference the POT.jl package in the README.
