### ISSUE TITLE
Transferring repo to an Github organisation?

### ISSUE THREAD

**Issue by zsteve** [JuliaOptimalTransport/OptimalTransport.jl#53]
Hi @davibarreira and @devmotion ,

I notice there's been quite some activity on the repo lately, and I'm delighted that the repo has had contributions!
Unfortunately in recent months this project has been on the backburner for me for personal and academic reasons, so apologies for my lack of presence (research shifted to a python codebase for compatibility issues and have been thesis-writing). 

Although I've added @devmotion as a contributor to the repo, I was thinking it might be a good idea to make a github organisation to host the repo instead of being on my personal github account. Perhaps this may make the contributing process smoother?

Edit: I imagine that this would be something that could be done perhaps not immediately, but in the near future.

Keen to hear any thoughts!

**Comment by devmotion** [comment]
I think that's a good idea, and POT.jl and StochasticOptimalTransport.jl would fit there as well (and probably better than in my private account). I just went on and created a JuliaOptimalTransport organization (https://github.com/JuliaOptimalTransport), and invited you to it. I've never transferred some of my repos to organizations before, the process is quite straightforward and smooth for Julia packages (and won't break the registry).

**Comment by devmotion** [comment]
BTW I would like to enable two-factor authentication for the organization to increase its security (it's common in many/most Julia organizations I know of) but this would require you to enable 2-FA in your accounts.

**Comment by davibarreira** [comment]
I'm all good. I already have a repo with JuliaGraphs, so I had to enable the 2-FA.

**Comment by davibarreira** [comment]
If possible, I think we should transfer to the Organizations ASAP.

**Comment by davibarreira** [comment]
@devmotion, do you want to use the Logo I've created to put in the organisation instead of the package? Otherwise, I can create another logo.

**Comment by zsteve** [comment]
> BTW I would like to enable two-factor authentication for the organization to increase its security (it's common in many/most Julia organizations I know of) but this would require you to enable 2-FA in your accounts.

I"ve activated 2FA, and I'll look into transferring the repo now.

**Comment by devmotion** [comment]
> I"ve activated 2FA, and I'll look into transferring the repo now. @devmotion would you be able to give me owner permissions in the org?

I've updated the security settings and changed your permissions. You should be able to initiate the transfer in OptimalTransport.jl, I guess then just someone from the organization has to accept it (it works even for repos from people that are not part of the organization I believe).

**Comment by zsteve** [comment]
Done! Was much simpler than I anticipated. Somehow didn't need an additional accept, probably since I'm in the target organisation.

**Comment by devmotion** [comment]
I moved StochasticOptimalTransport to the organization as well, and will do the same with PythonOT :+1: Just don't want to delay or disturb the registration process any further, I had to rename the package due to the guidelines and therefore I had to restart the registration process...
