### ISSUE TITLE
Process for adding new repos to the Julia Optimal Transport project

### ISSUE THREAD

**Issue by davibarreira** [JuliaOptimalTransport/OptimalTransport.jl#60]
Guys, I'd like to know what is the process for adding new repos to the Julia Optimal Transport project. For example, what are the criteria for a repo to be added to the project.
I have some repos that I'm working on, such as a repo with VegaLite visualizations for Optimal Transport and another of Hierarchical Clustering with OT. In the future, I'll probably do another one with Transfer Learning using OT (I think POT.py has something similar).

**Comment by devmotion** [comment]
There are no guidelines (yet) for JuliaOptimalTransport, and I'd argue that they are also not necessarily needed. From my experience with other organizations, I'd say one should be aware of the fact that it's not always good to move packages to an organization. It can increase outreach and discoverability but sometimes it can also lead to maintenance problems, e.g., if nobody feels responsible for the package anymore. Therefore I think this has to be decided case by case. I'd like packages to be already in a reasonable state (one shouldn't move a somewhat broken or unpolished package to an organization and then expect someone else to fix it) and someone (ideally multiple persons) in the organization should have an interest in using the package and maintaining it.

**Comment by davibarreira** [comment]
Sounds good.
