### ISSUE TITLE
Problem PreCompiling with Distributions

### ISSUE THREAD

**Issue by davibarreira** [JuliaOptimalTransport/OptimalTransport.jl#62]
I was updating my 1D Optimal Transport code, and before submitting, I pulled our updated master branch. After that, for some reason, when I try using the `Distributions.jl` types, such as `mu::UnivariateDistribution` , I get an error saying
```
ERROR: LoadError: UndefVarError: ContinuousUnivariateDistribution not defined
```

Here is how you can replicate it. Activate the environment in the Repl and add `Distributions.jl` as a dependency. After that, modify the `OptimalTransport.jl` file by adding any function using the `Distributions.jl` type, for example:
```
function optimal_transport_plan(
    c, μ::ContinuousUnivariateDistribution, ν::UnivariateDistribution
)
    # Use T instead of γ to indicate that this is a Monge map.
    T(x) = Distributions.quantile(ν, Distributions.cdf(μ, x))
    return T
end
```

And then you will get the error I just mentioned. Note that this was not happening in my first PR for the 1-D cases. It only happens now with the new master. I'm speculating it has something to do with the new dependencies, but I couldn't figure it out.

**Comment by devmotion** [comment]
I can't reproduce the issue with the following simple example: Everything works fine if I add Distributions as dependency, load it in OptimalTransport, and then define in the package
```julia
test(a::ContinuousUnivariateDistribution) = print(a)
```
I can also load the package and call the method without any problems.

**Comment by davibarreira** [comment]
What version of Julia? I'm trying to figure out what is going on here, if perhaps something with my Julia setup.

**Comment by devmotion** [comment]
Julia 1.6.1. Could it be a problem with the Unicode characters and/or your editor?

**Comment by devmotion** [comment]
And does it also happen in a fresh Julia session?

**Comment by davibarreira** [comment]
Ok. I have know idea what or why it happened. I just restarted everything (even the computer), and now it works. Sorry for bothering, I just didn't think restarting the computer would solve it, but it did.

**Comment by davibarreira** [comment]
Ok. I have know idea what or why it happened. I just restarted everything (even the computer), and now it works. Sorry for bothering, I just didn't think restarting the computer would solve it, but it did.
It was happening even with a fresh Julia session. I think it could've been something with VsCode also.

**Comment by davibarreira** [comment]
Yes, it's happening with a fresh session. No idea. I'll try changing branches. I'll delete my branch and start a new one. I'll be closing the PR for the 1D and submit another with all the modifications.
