### ISSUE TITLE
Function `emd` returning an error for an use case

### ISSUE THREAD

**Issue by davibarreira** [JuliaOptimalTransport/OptimalTransport.jl#71]
I'm trying to run the following case:
```julia
n = 2
distm = collect(Iterators.product(1:n,1:n));
μ = reshape(distm,n*n);
ν = reshape(distm,n*n);
C = Distances.pairwise(Distances.SqEuclidean(), μ, ν)
u = ones(n^2)/n^2
v = ones(n^2)/n^2
emd2(u,v,C,Tulip.Optimizer())
```
This is returning the following error, which I haven't been able to figure out yet:
``MathOptInterface.UnsupportedAttribute{MathOptInterface.ObjectiveFunction{MathOptInterface.ScalarAffineFunction{Int64}}}: Attribute MathOptInterface.ObjectiveFunction{MathOptInterface.ScalarAffineFunction{Int64}}() is not supported by the model.``

Any ideas?

**Comment by davibarreira** [comment]
So, it looks like the error is because the matrix `C` is composed of all integers. We should either fix the documentation and say that `C` has to be float, or fix the function. What do you guys think, @devmotion and @zsteve ?

**Comment by devmotion** [comment]
> I'll probably submit a PR this week adjusting the name and docs for all functions, so I'll also submit the fix.

Great, the documentation can definitely be improved (maybe take some inspiration from PythonOT?). If possible, it would be good to have separate PRs for documentation changes and bugfixes :slightly_smiling_face:
