### ISSUE TITLE
Adding support to parallelization with CUDA

### ISSUE THREAD

**Issue by davibarreira** [JuliaOptimalTransport/OptimalTransport.jl#73]
I'm not very versed on CUDA and code parallelization, but some of the stuff that I'm doing is starting to become too demanding. Hence, enabling parallelization and running on CUDA would be an interesting feature. What do you guys think? Do you thinks this is a feature we should support in the package?

**Comment by devmotion** [comment]
Have you checked if something does not work? E.g., `sinkhorn` and `sinkhorn2` should work with CUDA automatically since the code is written generically and just uses operations that are supported on GPUs. Due to the broadcasting it should also be quite efficient.

**Comment by davibarreira** [comment]
No. I'm doing this right now. My suggestion was to provide this out of the box, so people wouldn't need to write the CUDA.jl code themselves.

**Comment by devmotion** [comment]
There should be no need to write any CUDA code, it should just work :slightly_smiling_face: That's why I am asking if anything is broken.

**Comment by davibarreira** [comment]
-.-
Ok, perhaps I should have learned CUDA.jl, before posting the suggestion. My bad.

**Comment by davibarreira** [comment]
I'll close the issue until I have learned more about `CUDA.jl` myself. I don't know how to use sinkhorn with it. I've tried
`@cuda sinkhorn2(u,v,C,10)`, but it didn't work.

**Comment by devmotion** [comment]
One should only have to specify `mu`, `nu`, and `C` as `CuArray`s and then everything should run on the GPU.
