### ISSUE TITLE
`sinkhorn2` should return loss, not `dot(gamma, C)`

### ISSUE THREAD

**Issue by zsteve** [JuliaOptimalTransport/OptimalTransport.jl#74]
I noticed a problem with the current implementation of `sinkhorn2`: currently it is only returning the transport cost 
`dot(gamma, C)`, not the true Sinkhorn loss which includes the entropy penalty, i.e. `dot(gamma, C) + eps*dot(gamma, log.(gamma))`. It seems that PythonOT does the same thing (hence our unit tests work)?

What's strange is that consulting the PythonOT [docs](https://pythonot.github.io/all.html#ot.sinkhorn2), they say:
> Solve the entropic regularization optimal transport problem and return the loss.

@devmotion I think your docs in PythonOT.jl say "return the OT cost", which I interpret as being only the `dot(gamma, C)` component.

I think we should include the entropy penalty, since it's really part of what gives entropic OT its nice properties. For instance, the reason I caught this issue today was that I was trying to solve a variational problem using `dot(gamma, C)` as the loss and differentiating through `sinkhorn2`, but not having the entropy term makes the optimisation fail (I think due to lack of smoothness).

**Comment by zsteve** [comment]
The solution should be straightforward: just change `dot(gamma, C)` to `dot(gamma, C) + eps*dot(gamma, log.(gamma))`. But we will need to stabilize the log for cases where `gamma` may be zero, and we take `0*log(0) = 0`.

**Comment by zsteve** [comment]
> POT returns dot(gamma, C), as can be seen in the implementation (https://pythonot.github.io/_modules/ot/bregman.html#sinkhorn_knopp) and it is done on purpose it seems (PythonOT/POT#105 (comment)). So the documentation in PythonOT seems correct and I don't think the implementation should be changed since it would lead to inconsistencies with POT.

Thanks for the link. This seems strange to me, since the term `loss` should refer to the 'full' objective of an optimisation problem. Indeed, the solution offered by `sinkhorn2` is the one that minimises the loss, not cost `dot(gamma, C)`. If we want to support variational problems, then we should have some functionality that returns the loss. 

> Therefore I am not sure if there is enough reason for introducing a possibly surprising inconsistency with POT here. Maybe one could add a keyword argument that is disabled by default?

Yes agreed since the function naming is the same for now, we do not touch `sinkhorn2`. Although eventually we would move towards `sinkhorn_cost` and `sinkhorn_plan`, right? In which case I'd be in favour of adding a `sinkhorn_loss` for now. This is applicable to any regularisation actually, we can return either the `plan`, the `cost`, or the `loss`. 

> BTW if we add support for the regularized loss, we should just use dot(gamma, C) + eps * sum(LogExpFunctions.xlogx, gamma) which takes care of the case 0 * log(0) automatically.
thanks for pointing me to this package!

**Comment by davibarreira** [comment]
Again, I'm late to the discussion. But, what people usually call the "Sinkhorn distance" is actually just the cost of transportation of the optimal plan for the regularized, so both POT and our package are "correct" in returning `dot(gamma, C)`. Although, there is a lot of confusion with this in the literature, with people calling "sinkhorn distance" sometimes `dot(gamma, C)` and sometimes `dot(gamma, C) + eps*dot(gamma, log)`. We should really make it clear in the docs.
