### ISSUE TITLE
Dynamic Formulation for OT

### ISSUE THREAD

**Issue by davibarreira** [JuliaOptimalTransport/OptimalTransport.jl#78]
I'm starting to work on a solver using the dynamic formulation of OT (the Benamou-Brenier numerical method). I was wondering if such method should go in the main OptimalTransport.jl package, or if I should create a new package.

**Comment by devmotion** [comment]
I guess it's easier if you don't have to setup a new package, so I'd start with adding it to OptimalTransport at least initially. One can still move it to a separate package later on if we realize that this would be better.
